name: music_player_20
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.3
  audiotagger: ^2.2.1
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  http: ^1.2.2
  image_picker: ^1.1.2
  just_audio: ^0.9.38
  path_provider: ^2.1.3
  provider: ^6.1.2
  rxdart: ^0.28.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\images\travis.png
    - assets\images\Add_Image.png
    - assets\audio\90210.mp3
    - assets\images\music_logo.png

flutter_neumorphic: 
  git:
    url: https://github.com/den0206/Flutter-Neumorphic.git
    ref: feature/remoce_accentcolor